###############################################################################
#  service-base
#
#  Required arguments:
#    jdlapij_version
#    cream_utils_version
#
###############################################################################

FROM devel-base:centos7

ARG jdlapij_version
ARG cream_utils_version

LABEL jdl.api.java.version=${jdlapij_version} \
      cream.utils.version=${cream_utils_version}

RUN git clone https://github.com/italiangrid/cream-parent /var/lib/release/projects/cream-parent && \
    cd /var/lib/release/projects/cream-parent && mvn install

RUN git clone https://github.com/italiangrid/jdl-api-java /var/lib/release/projects/jdl-api-java && \
    cd /var/lib/release/projects/jdl-api-java && git checkout ${jdlapij_version} && \
    mvn -Drpm.repackaging=true -DskipTests install && \
    cp /var/lib/release/projects/jdl-api-java/target/rpmbuild/RPMS/noarch/*.rpm \
       /var/lib/release/dist/CREAM/centos7/noarch/base

RUN git clone https://github.com/italiangrid/cream-utils /var/lib/release/projects/cream-utils && \
    cd /var/lib/release/projects/cream-utils && git checkout ${cream_utils_version} && \
    mkdir build && cd build && cmake .. && make rpm && \
    cp /var/lib/release/projects/cream-utils/build/rpmbuild/RPMS/x86_64/*.rpm \
       /var/lib/release/dist/CREAM/centos7/x86_64/base

